### ISSUE TITLE
.sla file for MeP:LE:32:default has the wrong format

### ISSUE THREAD

**Issue by CelesteBlue-dev** [xyzz/ghidra-mep#2]
I use Ghidra 9.2 beta and the latest version of the precompiled ghidra-mep from release page.

```
Error importing file: second_loader.bin
ghidra.app.plugin.processors.sleigh.SleighException: .sla file for MeP:LE:32:default has the wrong format
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.restoreXml(SleighLanguage.java:850)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.readSpecification(SleighLanguage.java:842)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.initialize(SleighLanguage.java:133)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.<init>(SleighLanguage.java:101)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getNewSleigh(SleighLanguageProvider.java:112)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getLanguage(SleighLanguageProvider.java:99)
	at ghidra.program.util.DefaultLanguageService$LanguageInfo.getLanguage(DefaultLanguageService.java:394)
	at ghidra.program.util.DefaultLanguageService.getLanguage(DefaultLanguageService.java:111)
	at ghidra.app.util.opinion.BinaryLoader.loadProgram(BinaryLoader.java:274)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Dec-21 2208 CET
Ghidra Version: 9.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot
JVM Version: AdoptOpenJDK 11.0.4
OS: Windows 10 10.0 amd64
Workstation: MyPC.mshome.net
```

**Comment by xyzz** [comment]
Try removing the `.sla` file, IIRC it should trigger a recompile.

**Comment by CelesteBlue-dev** [comment]
I've done what you said and it works. Thanks.
Maybe this should be in the readme.
